---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-public-secrets
  namespace: launchblock-services
spec:
  encryptedData:
    API_TOKEN_SALT: AgA1yClwcnex53ZieoSeSFrqly4ARTi6Y5yXtTv/ki85RRSkXnL2c2bHEdN9eamW86hlBrX7wv+aci1O1f6W2hnuhW1PZCQHQVvLAKWlmOuLHjsILtPkokARaRMJ/YVWts/H07dpoT2eqwrfssVXGc+gvpSRcgSB09Q/1rh0IMDri+r18qmCbQPkk87uwSPRf6Ze9RLJ5oTPDX+AxE71WC0BtfbKO8GS4o6xt8taYgQEuHC/4nW4yts2yTruhPThR7QIexr9l0nz0a83jvthtB7/bz08ITI+xKwasQl1awr1/3MKCdbXgzpsAtBVF8HyT0GHF2ajoQfBXdePdl/4Ad1aBoQ+f+vY3WYiSYMCse7i8bpJj6cJcOHGec0XzREJ5f70QFF1sOBd/Z0ce5BvSr5qQwGUefGYZg/OQzk9ctR5Yiljf2UGVAO0xF2WRTdHst8WLJo/Wjp0gzVlXyZKWGYk0ApTUL3W3ZC+3lOFt8zQCpZiVRx2cVw8jHZEqXGD+g+bpY7ktbGZiJhbQaulICKouMj5SFxITJgzSNSvG18lOXf6pjiLvLq6/S54EDs5kP5eS0tm0qUA685Sdw+cHwe5K4ighfKpMzwUWJNARB+wPDYHBuLM12QkGFEkbPQCQ+e29wVnb5voMvVEmzHCz5f32DiXWYUwv+RI5+aswHjWt+WEQNTKWD0rTCjrXNyp1qsF1UgRjrkvgVHJiLrOMUtVXwKV93+zI+uykDPSVdRvBw==
    API_TOKEN_SECRET_KEY: AgAb4pqXwoKFqbsV11rhhyxVkhfJWSN2QrWjncs8CDvrcogSxPpI3qsZQzvn4B8vRtQnUciy6Hh3PuTHrfbTb1UQytTJFlq1ynFwPahU52USYADF0CUT8WVSbt9XGfUl1Ia3m08wKs6tKkoFwhKsZUKbTo0YUyQycJ7o/cwYorUrdN3T8Gfi9/7Kdh3VYkMvUsaQkqWc4mjHoIKr0JC6jU1eVc7XtaCaKGZoeZ5UK7IS+DPRbhD5vQvi6PTDG68DqfpcA1enYNydTcTq+RcjJdp783NQBnc0UGLyvVqPK6t3XLQms7KLtaSqHwtidQQQ6Sk/qBQeelDh4qdNaqyTFNae/V9B47hRLLuLq3l+2VGYxErICUVs1Oje0vyDogkX+Fdvt6nsMpeSzrno7lhwHGSUYVtwJtIiniyQ7GgYrHiC9eciah9MqFXzzQjs4j9KMrnmnrtOhaXOP4kOLuF/jccPe2437Zoti42+Hwfg2XjSPz+Y649RhqO6iRc7q42BBEn3eqBI1MBcaanpXk++Mso9STyrdLa1p9OXP8MUetANIJc8WKPysO7j2xwrE4IX0/TSb0ekBBYxontLlhK6joa+OQsm9WKcbeay8PRY63/SCGtKpodETZ7ZrAIamQJkZzFkAB0LoqHGnabD3UJ8hoE3yARdTRJLeDsgUiNsqfyvNC552ZcSNNlRmg7k+LQIxQeftWSKAnojIA54B+nFrJVJF8jy/Me++HznEeXDah9gxg==
  template:
    metadata:
      creationTimestamp: null
      name: api-public-secrets
      namespace: launchblock-services
    type: Opaque
